name: Build Docs

on: 
  push:
    branches-ignore: 
      - gh-pages

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1.0.0
    - name: Extract branch name
      shell: bash
      run: echo "::set-env name=GH_BRANCH::${GITHUB_REF##*/}"
    - name: Run CakeBuild script
      run: ./build.ps1 -target=Build -url_prefix=/bepinex_docs/ -branch_name="${GH_BRANCH}"
    - name: Push page to gh-pages
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_PAT }}
        branch: gh-pages
        directory: gh-pages
    
