name: Build Docs

on: 
  push:
    branches-ignore: 
      - gh-pages

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1.0.0
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.2
    - name: Run CakeBuild script
      run: | 
        chmod +x ./build.sh
        ./build.sh --target=Build --url_prefix=/bepinex_docs/ --branch_name="${GITHUB_REF##*/}"
    - name: Push page to gh-pages
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_PAT }}
        branch: gh-pages
        directory: gh-pages
    
