name: Build Docs

on: 
  push:
    branches-ignore: 
      - gh-pages

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1.0.0
    - name: Extract branch name
      shell: bash
      run: |
        echo Current branch: ${GITHUB_REF##*/}
        echo ::set-env name=GH_BRANCH::${GITHUB_REF##*/}
    - name: Run CakeBuild script
      run: ./build.ps1 -Target Build -ScriptArgs "-url_prefix=/bepinex_docs/ -branch_name=""${env:GH_BRANCH}"""
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      with:
        GH_PAT: ${{ secrets.GH_PAT }}
      env:
        BUILD_DIR: gh-pages
